<?php
 $title = 'My task list';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<div><?php echo $this->my?></div>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Content</th>
     <th>LoadCompleted?</th>
     <th>
       <p>
          <a href="<?php echo $this->url('task', array('action'=>'add'));?>">Add new item</a>
       </p>
     </th>
 </tr>
 <?php foreach ($tasks as $task): ?>
 <tr>
     <td>
         <?php echo $this->escapeHtml($task->getTitle()); ?>
     </td>
     <td><?php echo $this->escapeHtml($task->getContent()); ?></td>
     <td><?php echo $task->getContent() ? 'Yes' : 'No'; ?></td>
     <td>
         <a href="<?php echo $this->url('task',
             array('action'=>'delete', 'id' => $task->getId()));?>">[Delete]</a>||
         <a href="<?php echo $this->url('task',
             array('action'=>'edit', 'id' => $task->getId()));?>">[Edit]</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>