<h1>xumadd method</h1>
新闻标题: <input type="text" name="tttle" class="title" value="" /><br />
新闻内容: <input type="text" name="content" class="content" value="" /><br />
你的名字: <input type="text" name="name" class="name" value="" /><br />
你的性别: <select class="sex">
           <option value="boy" selected="selected">boy</option>
           <option value="girl">girl</option>
         </select><br />
喜欢球队: <select class="nbateam">
             <option value="03f41eb5656c333a3207d1162a6f216a" selected="selected">火箭</option>
             <option value="0f9012e9b12c0fff624cc91f1b865a92">开拓者</option>
             <option value="1105d832ff07b9fa3c3c07029dc7e5dd">老鹰</option>
             <option value="14198c44a4c0ae65cb23a544615d9418">太阳</option>
             <option value="fc6cff760a43730060c1601ef1fb41c8">勇士</option>
             <option value="1f9622d54781f79da17bbd9ab829bbf0">骑士</option>
             <option value="15fa659be1665f686f2392e01df2cb5d">步行者</option>
         </select><br />
<button class="submit">提交</button>