<h1>xumindex method</h1>
<div id="main_content">
新闻标题: <input type="text" name="title" class="title" value="请输入标题" /><br />
新闻内容: <input type="text" name="content" class="content" value="请输入内容" /><br />
你的名字: <input type="text" name="name" class="name" value="请输入名字" /><br />
你的性别: <select class="sex">
           <?php foreach ($this->sexInfo as $sex) : ?>
            <option value="<?php echo $sex; ?>"
               <?php
                 if($this->init_sex == $sex){
                    echo "selected=\"selected\"";
                  }
               ?>
            >
              <?php echo $this->escapeHtml($sex); ?>
            </option>
           <?php endforeach; ?>
         </select><br />
你的国家: <select name="country" class="country">
           <?php foreach ($this->countryInfo as $country) : ?>
            <option value="<?php echo $country; ?>"
              <?php
                 if($this->init_country == $country){
                    echo "selected=\"selected\"";
                  }
               ?>
            >
              <?php echo $this->escapeHtml($country); ?>
            </option>
           <?php endforeach; ?>
         </select><br />
喜欢球队: <select name="nbateam" class="nbateam">
           <?php foreach ($this->nbateamInfo as $nbateam) : ?>
            <option value="<?php echo $this->escapeHtml($nbateam->getId()); ?>"
              <?php
                 if($this->init_nbateam == $nbateam->getName()){
                    echo "selected=\"selected\"";
                  }
               ?>
            >
              <?php echo $this->escapeHtml($nbateam->getName()); ?>
            </option>
           <?php endforeach; ?>
         </select><br />
<button class="submit">提交</button>
</div>
<div style="text-align: center;">
 <a href="<?php echo $this->url('task',array('action'=>'xumlist'));?>">
     返回列表
 </a>
</div>
<div id="show" style="text-align: center;"></div>