<?php
 $title = 'My task list';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <table class="table">
 <tr>
     <th>姓名</th>
     <th>性别</th>
     <th>国家</th>
     <th>球队</th>
     <th>新闻</th>
     <th>
       <p>
         <a href="<?php echo $this->url('task',array('action'=>'xumindex'));?>">增加我的信息(测试用)</a>
      </p>
     </th>
 </tr>
 <?php foreach ($users as $user): ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->getName()); ?></td>
     <td><?php echo $this->escapeHtml($user->getSex()); ?></td>
     <td><?php echo $this->escapeHtml($user->getCountry()); ?></td>
     <td>
     <!-- 如果用view helper话,如$this->url(),这里的id参数必须和/checklist[/:action][/:id][/page/:page]的完全相同 -->
     <a href="<?php echo $this->url('task',
             array('action'=>'xumnbateam', 'id' => $user->getNbateamid())); ?>">[查看喜欢的球队信息]</a>
     ||<a href="#" onclick="showInfo('<?php echo $user->getNbateamid()?>')">[浮动]</a>
     </td>
     <td>
     <a href="<?php echo $this->url('task',
             array('action'=>'xumnews', 'id' => $user->getNewsid()));?>">查看发出的新闻信息</a>
     </td>
     <td>
         <a href="<?php echo $this->url('task',
             array('action'=>'xumdelete', 'id' => $user->getId()));?>">[Delete]</a>||
         <a href="<?php echo $this->url('task',
             array('action'=>'xumedit', 'id' => $user->getId()));?>">[Edit]</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>